version: '3'

services:
  app:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/jewellery-store-demo?authSource=admin
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=jewellery-store-demo
    volumes:
      - data:/data/db

volumes:
  data:
  node_modules:
